# -*- coding: utf-8 -*-
"""financial4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fl8p0bWuOMC6tyqgbknA7JzLEVkN_Z2L
"""

#!pip install streamlit

import streamlit as st
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

# Set the page title
st.title("Financial Dashboard")

# Sidebar input: prompt the user to enter a ticker symbol
ticker_symbol = st.sidebar.text_input("Enter the ticker symbol (e.g., AAPL)", value="AAPL")

if ticker_symbol:
    # Retrieve data for the entered ticker using yfinance
    ticker_data = yf.Ticker(ticker_symbol)
    info = ticker_data.info

    # ---------------------------
    # 1. Company Overview
    # ---------------------------
    st.subheader("Company Overview")
    if 'longBusinessSummary' in info:
        st.write(info['longBusinessSummary'])
    else:
        st.write("No overview available.")

    # ---------------------------
    # 2. Dividend History (Last 10 Entries)
    # ---------------------------
    st.subheader("Dividend History (Last 10 Entries)")
    dividends = ticker_data.dividends
    if dividends.empty:
        st.write("No dividend data available for this ticker.")
    else:
        # To avoid clutter, show only the last 10 entries if there are more than 10
        data_to_plot = dividends.tail(10) if len(dividends) > 10 else dividends
        st.write(data_to_plot)

        fig, ax = plt.subplots(figsize=(10, 4))
        ax.bar(data_to_plot.index.astype(str), data_to_plot)  # convert dates to string for clarity
        ax.set_title("Dividend History")
        ax.set_xlabel("Date")
        ax.set_ylabel("Dividend ($)")
        plt.xticks(rotation=45)
        st.pyplot(fig)

    # ---------------------------
    # 3. Price History (Last 1 Year)
    # ---------------------------
    st.subheader("Price History (Last 1 Year)")
    price_history = ticker_data.history(period="1y")
    if price_history.empty:
        st.write("No price data available for this ticker.")
    else:
        st.write(price_history[['Close']].head())  # display first few rows for preview
        fig_price, ax_price = plt.subplots(figsize=(10, 4))
        ax_price.plot(price_history.index, price_history['Close'], label="Closing Price")
        ax_price.set_title("Price History (Last 1 Year)")
        ax_price.set_xlabel("Date")
        ax_price.set_ylabel("Price ($)")
        ax_price.legend()
        st.pyplot(fig_price)

    # ---------------------------
    # 4. Key Financial Metrics
    # ---------------------------
    st.subheader("Key Financial Metrics")
    trailing_eps = info.get('trailingEps', None)
    dividend_rate = info.get('dividendRate', None)
    dividend_yield = info.get('dividendYield', None)

    # Calculate a simple dividend payout ratio (Dividend Rate / Trailing EPS) if possible
    if trailing_eps and trailing_eps != 0 and dividend_rate:
        dividend_payout_ratio = dividend_rate / trailing_eps
    else:
        dividend_payout_ratio = None

    st.write("**Trailing EPS:**", trailing_eps if trailing_eps is not None else "N/A")
    st.write("**Dividend Rate:**", dividend_rate if dividend_rate is not None else "N/A")
    st.write("**Dividend Yield:**", f"{dividend_yield:.2%}" if dividend_yield is not None else "N/A")
    if dividend_payout_ratio is not None:
        st.write("**Dividend Payout Ratio:**", round(dividend_payout_ratio, 2))
    else:
        st.write("Dividend payout ratio could not be calculated due to missing data.")

import yfinance as yf
import pandas as pd
import pprint

def compute_altman_z(ticker: str):
    """
    Compute the Altman Z-Score for a given ticker using data from yfinance.
    
    The Altman Z-Score (for manufacturing companies) is:
      Z = 1.2*(Working Capital/Total Assets) +
          1.4*(Retained Earnings/Total Assets) +
          3.3*(EBIT/Total Assets) +
          0.6*(Market Value of Equity/Total Liabilities) +
          (Sales/Total Assets)
    
    Parameters:
        ticker (str): The ticker symbol of the company.
    
    Returns:
        dict: A dictionary with the calculated ratios, Altman Z-Score, and classification,
              or None if essential data is missing.
    """
    t = yf.Ticker(ticker)
    
    # Try to fetch the required data:
    try:
        bs = t.balance_sheet       # Balance sheet DataFrame
        fs = t.financials          # Income statement DataFrame
        info = t.info              # General company info
    except Exception as e:
        print(f"Error retrieving data for {ticker}: {e}")
        return None

    # Use the most recent reporting period from the balance sheet/income statement
    try:
        bs_col = bs.columns[0]
    except Exception as e:
        print("Balance sheet data not available.")
        return None
        
    try:
        fs_col = fs.columns[0]
    except Exception as e:
        print("Financial (income statement) data not available.")
        return None

    # Retrieve individual financial items (using try/except to catch missing keys)
    try:
        total_assets = bs.loc['Total Assets'][bs_col]
    except Exception:
        total_assets = None

    try:
        total_liabilities = bs.loc['Total Liab'][bs_col]
    except Exception:
        total_liabilities = None

    try:
        # Sometimes labeled as "Total Current Assets" or "Current Assets"
        current_assets = bs.loc.get('Total Current Assets', bs.loc.get('Current Assets', None))
        if current_assets is not None:
            current_assets = current_assets[bs_col]
    except Exception:
        current_assets = None

    try:
        # Sometimes labeled as "Total Current Liabilities" or "Current Liabilities"
        current_liabilities = bs.loc.get('Total Current Liabilities', bs.loc.get('Current Liabilities', None))
        if current_liabilities is not None:
            current_liabilities = current_liabilities[bs_col]
    except Exception:
        current_liabilities = None

    # Compute Working Capital
    if current_assets is not None and current_liabilities is not None:
        working_capital = current_assets - current_liabilities
    else:
        working_capital = None

    try:
        retained_earnings = bs.loc['Retained Earnings'][bs_col]
    except Exception:
        retained_earnings = None

    try:
        # Use Operating Income as EBIT
        ebit = fs.loc['Operating Income'][fs_col]
    except Exception:
        ebit = None

    try:
        sales = fs.loc['Total Revenue'][fs_col]
    except Exception:
        sales = None

    try:
        # Market Value of Equity = Share Price * Shares Outstanding
        share_price = info.get('regularMarketPrice', None)
        shares_outstanding = info.get('sharesOutstanding', None)
        if share_price is not None and shares_outstanding is not None:
            market_value_of_equity = share_price * shares_outstanding
        else:
            market_value_of_equity = None
    except Exception:
        market_value_of_equity = None

    # Check that essential data is present
    if total_assets is None or total_liabilities is None or market_value_of_equity is None:
        print(f"Essential data not available for ticker {ticker}.")
        return None

    # Calculate the financial ratios used in the Z‑Score formula
    ratio1 = (working_capital / total_assets) if working_capital is not None else 0.0
    ratio2 = (retained_earnings / total_assets) if retained_earnings is not None else 0.0
    ratio3 = (ebit / total_assets) if ebit is not None else 0.0
    ratio4 = (market_value_of_equity / total_liabilities) if total_liabilities != 0 else 0.0
    ratio5 = (sales / total_assets) if sales is not None else 0.0

    # Calculate the Altman Z‑Score using the original coefficients for manufacturing firms:
    z_score = 1.2 * ratio1 + 1.4 * ratio2 + 3.3 * ratio3 + 0.6 * ratio4 + ratio5

    # Classify the company based on the Z‑Score:
    # - Z > 2.99: "Safe" (low likelihood of bankruptcy)
    # - 1.81 <= Z <= 2.99: "Grey Zone"
    # - Z < 1.81: "Distressed" (high risk)
    if z_score > 2.99:
        classification = "Safe"
    elif 1.81 <= z_score <= 2.99:
        classification = "Grey Zone"
    else:
        classification = "Distressed"

    # Prepare all the output data in a dictionary
    result = {
        "Ticker": ticker,
        "Total Assets": total_assets,
        "Total Liabilities": total_liabilities,
        "Working Capital": working_capital,
        "Retained Earnings": retained_earnings,
        "EBIT": ebit,
        "Sales": sales,
        "Market Value of Equity": market_value_of_equity,
        "Ratio1 (WC/TA)": ratio1,
        "Ratio2 (Retained Earnings/TA)": ratio2,
        "Ratio3 (EBIT/TA)": ratio3,
        "Ratio4 (MVE/TL)": ratio4,
        "Ratio5 (Sales/TA)": ratio5,
        "Altman Z-Score": z_score,
        "Classification": classification
    }
    return result


if __name__ == "__main__":
    ticker_input = input("Enter ticker symbol: ").strip()
    altman_data = compute_altman_z(ticker_input)
    if altman_data:
        print("\n=== Altman Z-Score Analysis ===")
        pprint.pprint(altman_data)
